# Generated by Django 3.2.7 on 2021-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='wassaf', max_length=255),
            preserve_default=False,
        ),
    ]
